// An array of "Essential hashtags".
var essentialHashtags = [
  "logoawesome",
  "logobloom",
  "logobrainy",
  "logodesigner",
  "logodesignersclub",
  "logoinspirations",
  "logoramia",
  "logoshift",
  "logosource",
  "logosupplies",
  "logoworlddesigners",
  "visualidentity"
];

// An array of "Additional hashtags".
var additionalHashtags = [
  "coollogo",
  "flatlogo",
  "goodlogo",
  "gridlogo",
  "logodesignlovers",
  "modernlogos",
  "bestlogo",
  "businesslogos",
  "corporatelogo",
  "creativelogo",
  "flatlogodesign",
  "greatlogo",
  "learnlogodesign",
  "lettermark",
  "logo_showcase",
  "logobook",
  "logoexcellent",
  "logofavs",
  "logofolio",
  "logogram",
  "logohero",
  "logoidea",
  "logoidentity",
  "logoimport",
  "logolemon",
  "logolist",
  "logologo",
  "logotix",
  "logotypeclub",
  "logowork",
  "logoworld",
  "logoxpose",
  "minimallogo",
  "modernlogo",
  "professionallogo"
];
